import Head from "next/head";
import {
  Box,
  Image,
  Heading,
  UnorderedList,
  ListItem,
  Link,
} from "@chakra-ui/react";

const Layout = ({ children, globalData }) => {
  const logo = globalData.mediaItems.nodes[0];
  const primaryMenu = globalData.menus.nodes.find(
    (menu) => menu.name === "Primary menu"
  );
  const footerMenu = globalData.menus.nodes.find(
    (menu) => menu.name === "Footer menu"
  );

  return (
    <>
      <Head>
        <title>
          {globalData.generalSettings.title} —{" "}
          {globalData.generalSettings.description}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Image
          src={logo.sourceUrl}
          alt={logo.altText}
          width={logo.mediaDetails.width}
          height={logo.mediaDetails.height}
        />
        <Heading mb={2}>{globalData.generalSettings.title}</Heading>
        <UnorderedList>
          {primaryMenu.menuItems.edges.map(({ node }) => (
            <ListItem key={node.id}>
              <Link href={node.path}>
                <a>{node.label}</a>
              </Link>
              {node.childItems.edges && (
                <UnorderedList>
                  {node.childItems.edges.map(({ node: childNode }) => (
                    <ListItem key={childNode.id}>
                      <Link href={childNode.path}>
                        <a>{childNode.label}</a>
                      </Link>
                    </ListItem>
                  ))}
                </UnorderedList>
              )}
            </ListItem>
          ))}
        </UnorderedList>
        <br />
        {children}
      </Box>
    </>
  );
};

export default Layout;
