import Head from "next/head";
import Link from "next/link";
import {
  Heading,
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbSeparator,
} from "@chakra-ui/react";

import { getProduct, getProductsSlugs } from "../../lib/api";

export default function Product({ product, preview }) {
  const createMarkup = () => {
    return { __html: product.content };
  };

  return (
    <>
      <Head>
        <title>Product detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading mb={2}>{product.title}</Heading>
      <Breadcrumb mb={2}>
        <BreadcrumbItem>
          <BreadcrumbLink as={Link} href="/">
            <a>Home</a>
          </BreadcrumbLink>
        </BreadcrumbItem>
        <BreadcrumbItem isCurrentPage>
          <BreadcrumbLink as={Link} href={`/product/${product.slug}`}>
            {product.title}
          </BreadcrumbLink>
        </BreadcrumbItem>
      </Breadcrumb>
      <div dangerouslySetInnerHTML={createMarkup()} />
    </>
  );
}

export async function getStaticPaths() {
  const products = await getProductsSlugs();

  const paths = products.edges.map(({ node }) => ({
    params: { slug: node.slug },
  }));

  return { paths, fallback: false };
}

export async function getStaticProps({ params, preview = false }) {
  const product = await getProduct(params.slug, preview);

  return {
    props: { product, preview },
  };
}
