import Head from "next/head";
import { useRouter } from "next/router";

import { getProduct, getProductsSlugs } from "../../lib/api";

export default function Product({ product, preview }) {
  return (
    <>
      <Head>
        <title>Product detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{product.title}</h1>
      </main>
      <footer>
        <p>Footer</p>
      </footer>
    </>
  );
}

export async function getStaticPaths() {
  const products = await getProductsSlugs();

  const paths = products.edges.map(({ node }) => ({
    params: { slug: node.slug },
  }));

  return { paths, fallback: false };
}

export async function getStaticProps({ params, preview = false }) {
  const product = await getProduct(params.slug, preview);

  return {
    props: { product, preview },
  };
}
