import Head from "next/head";
import Link from "next/link";

import { getProductsForHome } from "../lib/api";

export default function Home({ products: { edges }, preview }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Gurim</h1>
        <p>Recent posts</p>
        <ul>
          {edges.map(({ node }) => (
            <li key={node.id}>
              <Link href={`/product/${node.slug}`}>
                <a>{node.title}</a>
              </Link>
            </li>
          ))}
        </ul>
      </main>
      <footer>
        <p>Footer</p>
      </footer>
    </>
  );
}

export async function getStaticProps({ preview = false }) {
  const products = await getProductsForHome(preview);

  return {
    props: { products, preview },
  };
}
