import { Heading, UnorderedList, ListItem, Container } from "@chakra-ui/react";
import Head from "next/head";
import Link from "next/link";

import { getProductsForHome } from "../lib/api";

export default function Home({ products: { edges }, preview }) {
  return (
    <>
      <Head>
        <title>Gurim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading mb={2}>Gurim</Heading>
      <UnorderedList>
        {edges.map(({ node }) => (
          <ListItem key={node.id}>
            <Link href={`/product/${node.slug}`}>
              <a>{node.title}</a>
            </Link>
          </ListItem>
        ))}
      </UnorderedList>
    </>
  );
}

export async function getStaticProps({ preview = false }) {
  const products = await getProductsForHome(preview);

  return {
    props: { products, preview },
  };
}
